### ISSUE TITLE
How to configure asgi-correlation with loguru ? 

### ISSUE THREAD

**Issue by sorasful** [snok/asgi-correlation-id#7]
Hello there ! 

Loguru seems to get more popularity as time goes by, I've tried to setup a very minimal example to get your library working with it, but it seems it can't find the correlation id. 

I've tried several things, and right now i'm doing this : 

```python
import logging
import sys

import uvicorn
from asgi_correlation_id import CorrelationIdMiddleware
from fastapi import FastAPI
from loguru import logger

app = FastAPI()

app.add_middleware(CorrelationIdMiddleware)

# remove default handler
logger.remove()

fmt = "[{time}] [application_name] [{extra[correlation_id]}] [{level}] - {name}:{function}:{line} - {message}"
logger.add(sys.stderr, format=fmt, level=logging.DEBUG)

@app.get('/')
def index():
    logger.info(f"Request with id ")
    return 'OK'



if __name__ == '__main__':
    uvicorn.run(app)


```

And I get a : 

```bash
Record was: {'elapsed': datetime.timedelta(seconds=1, microseconds=1880), 'exception': None, 'extra': {}, 'file': (name='another_main.py', path='C:\\Users\\User\\PycharmProjects\\x\\y\\another_main.py'), 'function': 'index', 'level': (name='INFO', no=20, icon='ℹ️'), 'line': 21, 'message': 'Request with id ', 'module': 'another_main', 'name': '__main__', 'process': (id=3412, name='MainProcess'), 'thread': (id=9164, name='asyncio_0'), 'time': datetime(2021, 11, 17, 15, 7, 54, 443182, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600), 'Paris, Madrid'))}
Traceback (most recent call last):
  File "C:\Users\User\PycharmProjects\x\venv\lib\site-packages\loguru\_handler.py", line 155, in emit
    formatted = precomputed_format.format_map(formatter_record)
KeyError: 'correlation_id'
--- End of logging error ---
```

Got any idea ? Thanks !

**Comment by sorasful** [comment]
@sondrelg  Thanks for the quick reply ! 

So I tried to it like you said, but to avoid any confusion here's the code : 

```python 
import logging
import sys

import uvicorn
from asgi_correlation_id import CorrelationIdMiddleware, correlation_id_filter
from fastapi import FastAPI
from loguru import logger

app = FastAPI()

app.add_middleware(CorrelationIdMiddleware)

# remove default handler
logger.remove()

fmt = "[{time}] [application_name] [{correlation_id}] [{level}] - {name}:{function}:{line} - {message}"
logger.add(sys.stderr, format=fmt, level=logging.DEBUG, filter=correlation_id_filter(32))

@app.get('/')
def index():
    logger.info(f"Request with id ")
    return 'OK'


if __name__ == '__main__':
    uvicorn.run(app)

```

But unfortunately, I've got the same error e.g :  

```
...
Traceback (most recent call last):
  File "C:\Users\Utilisateur\User\x\venv\lib\site-packages\loguru\_handler.py", line 155, in emit
formatted = precomputed_format.format_map(formatter_record)
KeyError: 'correlation_id'
```

**Comment by sondrelg** [comment]
Ok, I'll take a closer look at this after work, in a few hours, and see if I can set up a working example 😊

**Comment by JonasKs** [comment]
I only had a few minutes to spare, and I've never touched `loguru`, so this might not be the correct solution. How ever, according to their documentation, filter functions are a bit [different](https://loguru.readthedocs.io/en/stable/resources/migration.html?highlight=(Filter)#replacing-logger-objects).

Keeping their syntax works:

```py
def correlation_id_filter(record):
    record['correlation_id'] = correlation_id.get()
    return record['correlation_id']


fmt = "[{time}] [application_name] [{correlation_id}] [{level}] - {name}:{function}:{line} - {message}"
logger.add(sys.stderr, format=fmt, level=logging.DEBUG, filter=correlation_id_filter)
```

**Comment by sorasful** [comment]
Wow, this works great! I wouldn't have thought about this.  

I just post this full example so people will know.


```python 
import logging
import sys

import uvicorn
from asgi_correlation_id import CorrelationIdMiddleware
from asgi_correlation_id.context import correlation_id
from fastapi import FastAPI
from loguru import logger

app = FastAPI()
app.add_middleware(CorrelationIdMiddleware)

# remove default handler
logger.remove()


def correlation_id_filter(record):
    record['correlation_id'] = correlation_id.get()
    return record['correlation_id']


fmt = "[{time}] [application_name] [{correlation_id}] [{level}] - {name}:{function}:{line} - {message}"
logger.add(sys.stderr, format=fmt, level=logging.DEBUG, filter=correlation_id_filter)


@app.get('/')
def index():
    logger.info(f"Request with correlation id ")
    return 'OK'


if __name__ == '__main__':
    uvicorn.run(app)
```

Thank you for your precious help and your time, I'll close this now :)

**Comment by ponponon** [comment]
Here's my example
```python
import logging
import sys

import uvicorn
from asgi_correlation_id import CorrelationIdMiddleware
# from asgi_correlation_id import correlation_id_filter
from asgi_correlation_id.context import correlation_id
from fastapi import FastAPI
from loguru import logger

app = FastAPI()

app.add_middleware(CorrelationIdMiddleware)

logger.remove()


def correlation_id_filter(record):
    record['correlation_id'] = correlation_id.get()
    return record['correlation_id']


fmt = "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level: <8}</level> | <red> {correlation_id} </red> | <cyan>{name}</cyan>:<cyan>{function}</cyan>:<cyan>{line}</cyan> - <level>{message}</level>"


logger.add(sys.stderr, format=fmt, level=logging.DEBUG,
           filter=correlation_id_filter)


@app.get('/')
def index():
    logger.info(f"Request with id ")
    return 'OK'

```
