### ISSUE TITLE
Integration with Uvicorn example can not run

### ISSUE THREAD

**Issue by ahaooahaz** [snok/asgi-correlation-id#87]
python version: 3.8.16
traceback:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 698, in add_filters
    filterer.addFilter(self.config['filters'][f])
  File "/usr/lib/python3.8/logging/config.py", line 324, in __getitem__
    value = dict.__getitem__(self, key)
KeyError: <asgi_correlation_id.log_filters.CorrelationIdFilter object at 0x7fad412e09a0>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/logging/config.py", line 563, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.8/logging/config.py", line 759, in configure_handler
    self.add_filters(result, filters)
  File "/usr/lib/python3.8/logging/config.py", line 700, in add_filters
    raise ValueError('Unable to add filter %r' % f) from e
ValueError: Unable to add filter <asgi_correlation_id.log_filters.CorrelationIdFilter object at 0x7fad412e09a0>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 36, in <module>
    uvicorn.run("test:app", port=8080, log_level=os.environ.get("LOGLEVEL", "DEBUG").lower())
  File "/home/zhanghao4/.local/lib/python3.8/site-packages/uvicorn/main.py", line 513, in run
    config = Config(
  File "/home/zhanghao4/.local/lib/python3.8/site-packages/uvicorn/config.py", line 272, in __init__
    self.configure_logging()
  File "/home/zhanghao4/.local/lib/python3.8/site-packages/uvicorn/config.py", line 364, in configure_logging
    logging.config.dictConfig(self.log_config)
  File "/usr/lib/python3.8/logging/config.py", line 808, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.8/logging/config.py", line 570, in configure
    raise ValueError('Unable to configure handler '
ValueError: Unable to configure handler 'access'
```

**Comment by sondrelg** [comment]
Sorry for never getting to this @ahaooahaz . Did you figure this out?

**Comment by AbdealiLoKo** [comment]
I have this same issue - and a bit iunsure about how to go ahead.
The example works for py3.11 but fails with the same error as above for py3.10

This works:
```
python                    3.10.14
fastapi                   0.115.4
asgi-correlation-id       4.3.4
uvicorn                   0.32.0
```

This does not works:
```
python                    3.11.9
fastapi                   0.115.4
asgi-correlation-id       4.3.4
uvicorn                   0.32.0
```

**Comment by sondrelg** [comment]
Can you post your log configration?

**Comment by AbdealiLoKo** [comment]
```py
from asgi_correlation_id import CorrelationIdFilter, CorrelationIdMiddleware, correlation_id
from uvicorn.config import LOGGING_CONFIG

LOGGING_CONFIG["handlers"]["default"]["filters"] = [CorrelationIdFilter(uuid_length=6, default_value="-")]
LOGGING_CONFIG["formatters"]["default"]["fmt"] = "%(asctime)s %(levelprefix)s [%(correlation_id)s] %(message)s"
LOGGING_CONFIG["handlers"]["access"]["filters"] = [CorrelationIdFilter(uuid_length=6, default_value="-")]
LOGGING_CONFIG["formatters"]["access"]["fmt"] = "%(asctime)s %(levelprefix)s [%(correlation_id)s] %(message)s"
app = FastAPI()
app.add_middleware(CorrelationIdMiddleware)
```

Now when I try 3.11 it works:
```bash
# uv venv venv3.11 --python 3.11 --seed
# venv3.11/bin/pip install fastapi[standard] asgi-correlation-id
# venv3.11/bin/fastapi dev run.py
....
2024-11-05 10:30:56,639 INFO:     [-] Application startup complete.
```

But with 3.10 it fails:
```bash
# uv venv venv3.10 --python 3.10 --seed
# venv3.10/bin/pip install fastapi[standard] asgi-correlation-id
# venv3.10/bin/fastapi dev run.py
....
ValueError: Unable to configure handler 'access'
```

**Comment by infnetdanpro** [comment]
Same, why was this issue closed?

**Comment by sondrelg** [comment]
Please try adjusting your config from this:

```python
LOGGING_CONFIG["handlers"]["default"]["filters"] = [CorrelationIdFilter(uuid_length=6, default_value="-")]
LOGGING_CONFIG["formatters"]["default"]["fmt"] = "%(asctime)s %(levelprefix)s [%(correlation_id)s] %(message)s"
LOGGING_CONFIG["handlers"]["access"]["filters"] = [CorrelationIdFilter(uuid_length=6, default_value="-")]
LOGGING_CONFIG["formatters"]["access"]["fmt"] = "%(asctime)s %(levelprefix)s [%(correlation_id)s] %(message)s"
```

to this:

```python
LOGGING_CONFIG["filters"] = {
    "correlation_id": {
        "()": "asgi_correlation_id.log_filters.CorrelationIdFilter",
        "uuid_length": 6,
        "default": "-,
    },
}
LOGGING_CONFIG["handlers"]["default"]["filters"] = ["correlation_id"]
LOGGING_CONFIG["formatters"]["default"]["fmt"] = "%(asctime)s %(levelprefix)s [%(correlation_id)s] %(message)s"
LOGGING_CONFIG["handlers"]["access"]["filters"] = ["correlation_id"]
LOGGING_CONFIG["formatters"]["access"]["fmt"] = "%(asctime)s %(levelprefix)s [%(correlation_id)s] %(message)s"
```
